23기 백선호 ADD: review POST기능 추가
wecode-bootcamp-korea/23-1st-Weeteweete-backend pull request #10
Opened 2021-08-11 06:52 UTC by preferbaik

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-11 11:12 UTC, lordmyshepherd requested changes

2021-08-11 11:12 UTC, lordmyshepherd commented on color.csv
> +color,
csv 파일은 github에 올라오지 않도록 수정해주세요~

2021-08-11 11:12 UTC, lordmyshepherd commented on concept.csv
> +concept,content
마찬가지 입니다.

2021-08-11 11:12 UTC, lordmyshepherd commented on image 복사본.csv
> +item,image,main
마찬가지 입니다.

2021-08-11 11:12 UTC, lordmyshepherd commented on products/views.py
> +
line 61, 62는 지워주세요.

2021-08-11 11:12 UTC, lordmyshepherd commented on products/views.py
> +                image_url = image,
image_url에 파일 형태로 저장하는 건가요??

2021-08-11 11:38 UTC, preferbaik commented on products/views.py
> +                image_url = image,
저희가 구현했던 코드에서는 form 데이터로 온 파일을 db에 생성하게 되면 파일명이 image_url column에 파일명이 저장되었습니다. 그리고 static 폴더 안에 form 데이터로 받은 파일이 자동으로 저장되었습니다. 이러한 방법이 문제가 있을까요???...

2021-08-11 11:38 UTC, preferbaik commented on products/views.py
> +
수정했습니다~

2021-08-11 11:38 UTC, preferbaik commented on image 복사본.csv
> +item,image,main
수정했습니다~

2021-08-11 11:38 UTC, preferbaik commented on concept.csv
> +concept,content
수정했습니다~

2021-08-11 11:38 UTC, preferbaik commented on color.csv
> +color,
네네~~

2021-08-12 01:58 UTC, redsaumon commented on products/views.py
> +                image_url = image,
아니요 문제되지는 않습니다! 하지만 요즘엔 잘 사용하지 않는 방식입니다. 아마존에서 제공하는 스토리지 서비스인 s3에 파일을 저장하고 url만 따오는 방식을 주로 사용하는데, 위와 같이 백엔드 서버 자체에 파일을 저장하게 될 경우 무거워지고 관리하기 어렵습니다. 보안상 문제가 생길 수도 있어 웹서버와 파일서버를 분리하는 것을 추천합니다.

2021-08-12 01:58 UTC, redsaumon commented on products/views.py
> +    def post(self, request, item_id):
item이 존재하지 않을 경우도 로직에 넣어주세요.

2021-08-12 02:48 UTC, preferbaik commented on products/views.py
> +    def post(self, request, item_id):
수정했습니다~

2021-08-12 02:48 UTC, preferbaik commented on products/views.py
> +                image_url = image,
네넵!

2021-08-12 02:53 UTC, redsaumon commented
수고하셨습니다 선호님!:+1:

2021-08-12 02:53 UTC, merged