Cart CRUD
wecode-bootcamp-korea/23-1st-Weeteweete-backend pull request #9
Opened 2021-08-09 06:15 UTC by preferbaik

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-09 06:16 UTC, Jongseong0111 commented
<img width="1032" alt="Cart Delete" src="https://user-images.githubusercontent.com/84963683/128666467-5311b4ed-1e51-4bcd-a5db-3e2de3aba0d6.png">
<img width="1440" alt="Cart Get" src="https://user-images.githubusercontent.com/84963683/128666470-90c863c6-97cf-4871-9577-01f1b41c8bd1.png">

2021-08-09 06:17 UTC, Jongseong0111 commented
POSTMAN 자료 더 필요하면 더 올리겠습니다!

2021-08-10 04:41 UTC, lordmyshepherd requested changes
먼저, Order, Cart 모든 기능을 하나의 PR로 만들어서 올리는 습관은 좋지 않습니다.
그 이유는 Order 기능은 완벽해서 main branch에 merge해도 되는 상황인데 Cart 기능에 수정사항 때문에 Order 기능까지 작업이 지체되기 때문입니다~

2021-08-10 04:41 UTC, lordmyshepherd commented on orders/views.py
>          if Order.objects.filter(member_id = request.user.id, status_id = 1).exists():
`status_id = 1`로 하게되면, 1번이 의미하는게 무엇인지는 작성한 사람만 알 수 있습니다.
그래서 이런경우에는 Enum으로 status를 관리해야줘야 합니다. 아래 예제를 참고해서 만들어보세요.

예를 들면 아래와 같이 코드를 작성하셔야 합니다.
```python
class OrderStatus(models.Model):
    class Status(models.IntegerChoices):
        CANCLED   = 1
        COMPLETED = 2
```
!! 여기서 주의해야될 점은 `CANCLED   = 1`은 OrderStatus 테이블에 저장된 값과 동일하게 관리해야된다는 점입니다.
status table
```
id  |  name
1   | CANCLED
2   | COMPLETED
```

```suggestion
        if Order.objects.filter(member_id = request.user.id, status_id = OrderStatus.CANCLED.value).exists():
```

2021-08-10 04:41 UTC, lordmyshepherd commented on orders/views.py
>              Order.objects.filter(member_id = request.user.id, status_id = 1).delete()
여기서 `status_id=1`을 다시 왜 지워주는지 설명해주실 수 있나요?

2021-08-10 04:41 UTC, lordmyshepherd commented on orders/views.py
> +                    order_item_status_id = 1,
여기도 마찬가지로 `Enum`으로 관리해주세요~

2021-08-10 04:41 UTC, lordmyshepherd commented on orders/views.py
>          )
item_id를 받는 경우와 받지 않는 경우는 어떤 경우인가요?

2021-08-10 04:41 UTC, lordmyshepherd commented on orders/views.py
> +                return JsonResponse({"MESSAGE":"CART_EXIST"}, status=400)
중복되는 경우는 `409`를 반환합니다.

```suggestion
            if Cart.objects.filter(Q(item_id = data['item_id']) & Q(member_id=request.user.id)).exists():
                return JsonResponse({"MESSAGE":"CART_ALEADY_EXIST"}, status=409)
```

2021-08-10 04:41 UTC, lordmyshepherd commented on orders/views.py
> +            )
주문 수량과 재고를 비교한 후에 카트를 생성하는데, 카트에 담긴 이후에 재고 관리는 어디서 해주는건가요?

2021-08-10 04:41 UTC, lordmyshepherd commented on orders/views.py
> +        return JsonResponse({"RESULT" : results}, status=201)
조회, 업데이트에 사용되는 status code는 200입니다.

```suggestion
    @login
    def get(self, request):

        if not Cart.objects.filter(member_id=request.user.id).exists():
                return JsonResponse({"MESSAGE":"EMPTY_CART"}, status=400)

        results = [
            {
            "cart_id"  : cart.id,
            "item_id"  : cart.item.id,
            "quantity" : cart.quantity,
            "name"     : cart.item.name,
            "image"    : cart.item.image_set.get(main=1).image_url,
            "price"    : cart.item.price,
            "discount" : cart.item.discount
            } 
        for cart in Cart.objects.filter(member_id=request.user.id)]

        return JsonResponse({"RESULT" : results}, status=200)
```

2021-08-10 04:41 UTC, lordmyshepherd commented on orders/views.py
> +        return JsonResponse({"RESULT" : results}, status=201)
나머지는 👍

2021-08-10 04:41 UTC, lordmyshepherd commented on orders/views.py
> +        cart_id = request.GET.get("cart_id", None)
update할 때 받는 데이터를 query parameter로 받는 이유가 있나요?
생성, 업데이트에 사용되는 데이터는 payload 즉 body에 담아서 보내주는 것이 알반적으로 사용하는 방법입니다.

2021-08-10 04:41 UTC, lordmyshepherd commented on orders/views.py
> +        return JsonResponse({"MESSAGE" : "SUCCESS"}, status=200)
cart를 하나씩 지우는 방식을 구현 하신다면, `DELETE /carts/<int:cart_id>` 형태로 구현해야 하지만, 위 케이스처럼 전체 상품도 삭제해야되는 경우는, `DELETE /carts?ids=[1,2,3,5]`로 받아서 삭제하도록 구현해주세요. 그래야만 한개를 삭제할 수도, 여러개를 삭제할 수도 있습니다.

```suggestion
    @login
    def delete(self, request):
        is_all = request.GET.get("is_all", None)
        cart_id = request.GET.get("cart_id", None)

        if not is_all:
            Cart.objects.get(id = cart_id).delete()
            return JsonResponse({"MESSAGE" : "DELETE"}, status=200)

        Cart.objects.filter(member_id = request.user.id).delete()
        
        return JsonResponse({"MESSAGE" : "SUCCESS"}, status=200)
```

2021-08-10 04:41 UTC, lordmyshepherd commented on orders/views.py
> +        return JsonResponse({"MESSAGE" : "SUCCESS"}, status=200)
추가로 자원을 삭제했으면 status 코드는 204를 반환합니다.
```python
        return JsonResponse({"MESSAGE" : "NO_CONTENT"}, status=204)
```

2021-08-10 05:27 UTC, Jongseong0111 commented on orders/views.py
>              Order.objects.filter(member_id = request.user.id, status_id = 1).delete()
stauts_id=1이면 구매하기 전 대기 상태이고 id=2는 결제하여 구매가 완료된 상태입니다.
결제 페이지에서 GET 요청에 반환하는 값이 구매하기 전 대기 상태인 status=1의 Item들이고,  결제를 하면 status=2로 업데이트됩니다.
만약 결제를 하지 않고 새로운 상품을 Order하면 그 상품들만 GET 요청에 return되야하기에 원래 존재했던 status=1 아이템을 지웠습니다.

2021-08-10 05:30 UTC, Jongseong0111 commented on orders/views.py
>              Order.objects.filter(member_id = request.user.id, status_id = 1).delete()
지우는 것이 바람직하지 않다면 '결제까지 하지 않았다'는 뜻의 status를 추가해서 update 할까요?

2021-08-10 05:31 UTC, preferbaik commented on orders/views.py
>          )
장바구니에서 직접 구매할 경우에는 item_id를 받지 않고 장바구니를 거쳐 구매할 경우 item_id를 받습니다 .

2021-08-10 05:35 UTC, Jongseong0111 commented on orders/views.py
>          )
상세페이지에서 구매할 경우 하나의 item만 구매 가능하고, 장바구니에서 구매할 경우 다수의 item을 구매할 수 있어 분리해놓았습니다.

2021-08-10 05:35 UTC, preferbaik commented on orders/views.py
> +            )
결제를 진행해야 item 테이블의 stock에서 구매한 수량만큼 재고가 줄어듭니다. 따라서 장바구니에 담았을때는 item테이블의 stock을 참조하여 비교합니다.

2021-08-10 07:25 UTC, preferbaik commented on orders/views.py
>          if Order.objects.filter(member_id = request.user.id, status_id = 1).exists():
수정내용 모두 반영했습니다~~!

2021-08-10 10:55 UTC, lordmyshepherd commented on orders/views.py
>              Order.objects.filter(member_id = request.user.id, status_id = 1).delete()
기획 자체가 결제를 하지 않고 새로운 상품을 주문하면, 해당 상품만 리턴해줘야 한다면 지워주는 방법이 좋겠네요~
👍

2021-08-10 11:09 UTC, lordmyshepherd commented on orders/views.py
>          )
상세페이지에서 직접 구매하는 경우나 장바구니에 있는 상품들을 구매하는 경우나, 여러개를 생성할 수 있게 만들면 해결될 문제 같습니다~

Input

```python
[
    {
        “Item_id” : 1,
        “quantity” : 5,
    },
    {
        “Item_id” : 1,
        “quantity” : 5,
    }
]
```

그래서 결과적으로는 bulk insert 해서 데이터를 저장할 수 있는 방향으로 수정하시면 좋을 것 같습니다~
```python
OrderItems.objects.bulk_create(
    [OrderItems(item_id=.., quantity=..]

```

2021-08-11 01:31 UTC, preferbaik commented on orders/views.py
>          )
item_id를 받을경우 반복문을 한번만 돌리는 방식을 사용해서 기존에 있던 코드를 한번에 만들어 질수 있게 하였습니다.~

2021-08-11 02:54 UTC, lordmyshepherd requested changes

2021-08-11 02:54 UTC, lordmyshepherd commented on orders/views.py
> +
line 106~108 지워주세요~

2021-08-11 02:54 UTC, lordmyshepherd commented on orders/views.py
>          )
잘 수정해주셨네요~👍  
Align만 맞춰주세요 ㅎㅎㅎ

```suggestion
        OrderItem.objects.bulk_create(
            [OrderItem(
                item_id              = cart.item_id if not item_id else item_id, 
                order_id             = order.id, 
                quantity             = cart.quantity if not item_id else data['quantity']
                order_item_status_id = OrderItemStatus.ItemStatus.WAITING.value, 
            ) for cart in (Cart.objects.filter(member_id = request.user.id) if not item_id else range(1))]
        )
```

2021-08-11 02:54 UTC, lordmyshepherd commented on orders/views.py
>          )
[참고] 이번에 수정하라는 얘기는 아니고 다음에는 아래와 같이 수정해보세요.
반드시 카트 테이블에 저장되어 있는 값으로 주문할 필요가 없고, 카트에 담겨져있는 상품의 id와 수량을 직접 리스트로 받아서 저장하도록 만들면 훨씬 로직이 간단해지고 나중에 `디버깅`하기도 쉬워집니다!

```suggestion
        items = data["items"]
        ..
        OrderItem.objects.bulk_create(
            [OrderItem(
                item_id   = item["id"],
                order_id  = order.id, 
                quantity  = item["quantity"]
                status_id = OrderItemStatus.ItemStatus.WAITING.value
            ) for item in items]
```

2021-08-11 03:08 UTC, preferbaik commented on orders/views.py
> +
반영 했습니다~~

2021-08-11 03:08 UTC, preferbaik commented on orders/views.py
>          )
감사합니다~~

2021-08-11 06:15 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-08-11 06:16 UTC, merged